% Figures to visualize data

% gscatter(feature(:,1),feature(:,3),label)
% legend('normal','fault')
% set(legend,'FontSize',11);

figure;
plot(t_gyro_nominal_cond(17000:end), gyro_nominal_cond(17000:end,1));
hold on;
plot(t_gyro_fault_cond,gyro_fault_cond(:,1));
xlim([t_gyro_nominal_cond(17000) t_gyro_fault_cond(end)])
xlabel({'$t(s)$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',15,...
'FontName','Times')
ylabel({'$\omega_x$'},...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',15,...
'FontName','Times')
print -depsc2 gyro_x.eps